### PR TITLE
Fixes mainadm repo validation failure

### LINKED ISSUE #124: cmt-mainadm should honour the studentify. common-project-enable setting
When running `cmt-mainadm` on a project that has `common-project-enable` set to `false`, it still reports that there is no `common` project in the repo.

### PR DESCRIPTION
**Pull request by robinraju**
Fixes #124 

Use config entries from `course-management.conf` for validating course repo.

### CODE REVIEW

File: core/src/main/scala/com/lightbend/coursegentools/Helpers.scala [hunk 1]
```diff
@@ -149,8 +149,10 @@ object Helpers {
         new File(projectFolder, "README.md")
     }
 
+    val commonProject = if (config.commonProjectEnabled) "common" else ""
+
     // Check all required README files are present
-    for { project <- "common" +: exercises} {
+    for { project <- commonProject +: exercises} {
```
Comment (eloots) [inline core/src/main/scala/com/lightbend/coursegentools/Helpers.scala:155]: Isn't this a bit of a hack in the sense that, in the case that `config.commonProjectEnabled` is `false`, it will test the presence of the base folder?

Comment (robinraju) [reply core/src/main/scala/com/lightbend/coursegentools/Helpers.scala:155]: yes, if the setting is false, it will check the base folder. 
And I just found the error message is not printing the path based on the config. I'll update this PR.

Comment (eloots) [reply core/src/main/scala/com/lightbend/coursegentools/Helpers.scala:155]: I would instead create a modified `exercises` value that has conditionally added a "common" element to it.
The addition of an empty string is a burden on anyone who's reading the code for the first time.
so something like:
```
val exercises_ammended = if (config.commonProjectEnabled) "common" +: exercises else exercises
...
for { project <- exercises_ammended) {
...
```

Comment (robinraju) [reply core/src/main/scala/com/lightbend/coursegentools/Helpers.scala]: I've updated the code in the last commit in a similar fashion
